## 1.线性回归demo

In [25]:
import  torch
import torch.nn as nn
class LinearModel(nn.Module):
    def __init__(self, ndim):
        super(LinearModel, self).__init__()
        self.ndim  = ndim

        self.weight = nn.Parameter(torch.randn(ndim, 1)) 
        self.bias = nn.Parameter(torch.randn(1))
    def forward(self, x):
        # y= Wx + b 
        return x.mm(self.weight) + self.bias

print(torch.__version__) 


2.0.1+cu118


In [29]:
lm = LinearModel(5)
x = torch.randn(4,5)  # batch 为4
lm(x), lm

(tensor([[-1.3832],
         [-0.8377],
         [-1.4740],
         [-1.6321]], grad_fn=<AddBackward0>),
 LinearModel())

In [18]:
dir(lm)

['T_destination',
 '__annotations__',
 '__call__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_apply',
 '_backward_hooks',
 '_backward_pre_hooks',
 '_buffers',
 '_call_impl',
 '_forward_hooks',
 '_forward_hooks_with_kwargs',
 '_forward_pre_hooks',
 '_forward_pre_hooks_with_kwargs',
 '_get_backward_hooks',
 '_get_backward_pre_hooks',
 '_get_name',
 '_is_full_backward_hook',
 '_load_from_state_dict',
 '_load_state_dict_post_hooks',
 '_load_state_dict_pre_hooks',
 '_maybe_warn_non_full_backward_hook',
 '_modules',
 '_named_members',
 '_non_persistent_buffers_set',
 '_parameters',
 '_register_load_state_dict_pre_hook',
 '_register_sta

In [19]:
lm.named_parameters(), list(lm.named_parameters())

(<generator object Module.named_parameters at 0x0000011E607A3F40>,
 [('weight',
   Parameter containing:
   tensor([[-0.8593],
           [ 1.0687],
           [-0.0311],
           [ 0.9709],
           [ 0.5852]], requires_grad=True)),
  ('bias',
   Parameter containing:
   tensor([0.3763], requires_grad=True))])

In [20]:
lm.cuda() # 将 模型参数转移到GPU 上，注意 device='cuda:0'
list(lm.named_parameters())

[('weight',
  Parameter containing:
  tensor([[-0.8593],
          [ 1.0687],
          [-0.0311],
          [ 0.9709],
          [ 0.5852]], device='cuda:0', requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([0.3763], device='cuda:0', requires_grad=True))]

In [21]:
lm.half()  # 转换模型参数为半精浮点数

LinearModel()

In [22]:
list(lm.named_parameters())


[('weight',
  Parameter containing:
  tensor([[-0.8594],
          [ 1.0684],
          [-0.0311],
          [ 0.9707],
          [ 0.5854]], device='cuda:0', dtype=torch.float16, requires_grad=True)),
 ('bias',
  Parameter containing:
  tensor([0.3762], device='cuda:0', dtype=torch.float16, requires_grad=True))]

In [23]:
lm.state_dict()

OrderedDict([('weight',
              tensor([[-0.8594],
                      [ 1.0684],
                      [-0.0311],
                      [ 0.9707],
                      [ 0.5854]], device='cuda:0', dtype=torch.float16)),
             ('bias', tensor([0.3762], device='cuda:0', dtype=torch.float16))])

## 2.  求导

In [8]:
import torch  
import numpy as np

t1 = torch.randn(3,3, requires_grad=True)
t1

tensor([[ 0.9360, -0.4411, -0.7872],
        [ 0.1219, -0.3136,  0.4278],
        [-1.1784,  0.8631, -0.1838]], requires_grad=True)

In [9]:
t2= t1.pow(2).sum()  # t2 = t1^2
t2

tensor(4.1539, grad_fn=<SumBackward0>)

In [10]:
t2.backward()

In [11]:
t1.grad

tensor([[ 1.8719, -0.8823, -1.5745],
        [ 0.2438, -0.6271,  0.8556],
        [-2.3568,  1.7261, -0.3677]])

In [12]:
t2= t1.pow(2).sum()  # t2 = t1^2
t2.backward()
t1.grad


tensor([[ 3.7438, -1.7646, -3.1489],
        [ 0.4875, -1.2543,  1.7112],
        [-4.7136,  3.4523, -0.7354]])

In [13]:
t1.grad.zero_() # 梯度清零


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [14]:
t1.grad


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [15]:
t2.backward()

RuntimeError: Trying to backward through the graph a second time (or directly access saved tensors after they have already been freed). Saved intermediate values of the graph are freed when you call .backward() or autograd.grad(). Specify retain_graph=True if you need to backward through the graph a second time or if you need to access saved tensors after calling backward.